### ISSUE TITLE
Unable to change email inbox password

### ISSUE THREAD

**Issue by ptitfred** [yadutaf/ovh-cli#12]
Here is the call failing to change the password (with fake infos):

```
$ ./ovh-eu email-domain my-domain.com account some.user change-password create --password p4ssw0rd
usage: POST /email/domain/my-domain.com/account/some.user/changePassword
       [-h] --password PASSWORD
POST /email/domain/my-domain.com/account/some.user/changePassword: error: argument --password: invalid loads value: 'p4ssw0rd'
```

(It doesn't reach the API call itself, so no `--debug` info.)

**Comment by yadutaf** [comment]
I should add a disclaimer in the README: "The code is a pile of Hacks. Use it at your own risks" ;) Anyway, i pushed a commit. That will fix this route. And hopefully not break the other ones... At least the renew routes are working now.

I know how I can add tests to this code. Just not enough spare time...

**Comment by ptitfred** [comment]
No problem man, I'm just willing to help :)
