### ISSUE TITLE
api email Unknown route

### ISSUE THREAD

**Issue by Sylvain303** [yadutaf/ovh-cli#14]
It doesn't see email API?
Or did I miss something?

[GET /email/domain/{domain}](https://eu.api.ovh.com/console/#/email/domain/%7Bdomain%7D#GET)

~~~
./ovh-eu email help
Unknown route /email
~~~

**Comment by yadutaf** [comment]
The trick is: there is no top level "email" API. There are 3 sub-level APIs though:

```
./ovh-eu --help | grep email
    email-imap-copy                 Copy messages between two mailboxes
    email-exchange                  Operations about the EXCHANGE service
    email-domain                    Operations about the MX service
```

**Comment by Sylvain303** [comment]
OK, thanks.

What is the "algorithm" to convert from REST url to command line?
When (why) such "trick" appears?

**Comment by yadutaf** [comment]
Each top level API is mapped to a top level command. Some top level commands have a "/" in it, it is replaces by a '-'
