### ISSUE TITLE
non-lowercase API routes are unknown

### ISSUE THREAD

**Issue by noone1337** [yadutaf/ovh-cli#4]
Hi, 

non-lowercase API route are unkown:

$ ./ovh-eu msServices
Unknown route /msServices

$ ./ovh-eu newAccount
Unknown route /newAccount

$ ./ovh-eu ipLoadbalancing
Unknown route /ipLoadbalancing

-- Robert

**Comment by noone1337** [comment]
Hi yadutaf, 

ok, found it in the code... 
You convert camel case (eg msServices) to snake case (eg ms-services).
./ovh-eu ms-services / new-account / ip-loadbancing works.

This should be documented in the README :-)

-- Robert

**Comment by yadutaf** [comment]
Thanks for the report. I'll see If I can add some aliases too. Pro-tip: try "./ovh-eu help" ;)

**Comment by noone1337** [comment]
./ovh-eu **--**help shows me all available commands :-) Sorry for that.
